
[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"
optimizer = true
optimizer_runs = 200
via_ir = false

# 映射 OpenZeppelin 合约路径
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/"
]

# Polygon 网络配置
[rpc_endpoints]
polygon = "https://polygon-rpc.com"
amoy = "https://rpc-amoy.polygon.technology"

# Gas 报告
gas_reports = ["*"]